[versions]
project = "0.1.8-SNAPSHOT"
java = "25"
minecraft = "26.1-snapshot-5"

fabric_loom="1.15-SNAPSHOT"
fabric_loader="0.18.4"

[plugins]
fabric_loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric_loom" }

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }